version: '2'
services:
  app:
    build: .
    command: "true"
    volumes:
      - .:/upaya
  web:
    extends:
      service: app
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: "redis://redis"
      DATABASE_URL: "postgres://postgres@db"
    depends_on:
      - db
      - redis
      - worker
  worker:
    extends:
      service: app
    command: "bundle exec sidekiq -q sms -q voice -q mailers -q analytics"
    environment:
      REDIS_URL: "redis://redis"
      DATABASE_URL: "postgres://postgres@db"
      SMTP_HOST: "mailcatcher"
    depends_on:
      - db
      - redis
      - mailcatcher
  db:
    image: postgres
  redis:
    image: redis
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1080:1080
